export enum LoanEligibilityCards {
  OPEN = 'NEW-LOAN-REAPPLY-OPEN',
  CLOSED = 'NEW-LOAN-REAPPLY-CLOSED',
  CANT_ASSIST = 'CANT-ASSIST-NOW',
  NO_SERVICE = 'CANT-ASSIST-NO-SERVICE',
}

export const EligibleCards = [
  'NEW-LOAN-REAPPLY-OPEN',
  'NEW-LOAN-REAPPLY-CLOSED',
];
