name: Init Netlify Project

on:
  push:
    branches:
      - master

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Netlify CLI
        run: npm install -g netlify-cli
      
      - name: Initialize Netlify Project
        run: |
              SITE_DATA=$(netlify sites:create --name pfi-bkm-personal-information-v1-mfe-actions-test --account-slug purpose-financial)
              echo "$SITE_DATA"
              SITE_ID=$(echo "$SITE_DATA" | grep 'Site ID:' | awk '{{print $3}}')
              echo "SITE_ID=$SITE_ID" >> $GITHUB_ENV
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
