name: Init Netlify Project

on:
  push:
    branches:
      - master

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
          - name: Checkout code
            uses: actions/checkout@v2
          - name: List files in working directory
            run: ls -la
          - name: Link GitHub Repository
            run: netlify link --id 84934ec4-08f3-4e3d-acf5-b224b85c15ac
            env:
              #NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
              NETLIFY_AUTH_TOKEN: "nfp_v6V4gcmStJXdSaQAx1W15sqYFX9bVB4M2bd3"
