name: Build and Deploy to Netlify
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          NETLIFY_AUTH_TOKEN: "nfp_45oNycghjHD2eShaAiLdxwjBQXNejd7za901"
          publish-dir: './dist'
          production-branch: develop
          netlify-site-name: "pfi-bkm-lap-dashboard-v1-mfe"
          github-token: ${{ secrets.TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        timeout-minutes: 1
