name: Init Netlify Project

on:
  push:
    branches:
      - master

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Netlify CLI
        run: npm install -g netlify-cli
      
      - name: Initialize Netlify Project
        run: |
              SITE_DATA=$(netlify sites:create --name pfi-bkm-personal-information-v1-mfe-actions --account-slug team-purpose)
              echo &quot;$SITE_DATA&quot;
              SITE_ID=$(echo &quot;$SITE_DATA&quot; | grep &#39;Site ID:&#39; | awk &#39;{{print $3}}&#39;)
              echo &quot;SITE_ID=$SITE_ID&quot; &gt;&gt; $GITHUB_ENV
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
