name: Build and Deploy to Netlify
on:
  push:
  pull_request:
jobs:
  deploy-production:
    name: Deploy production site
    runs-on: ubuntu-latest
    if: always()
    environment:
      name: production
      url: ${{ steps.deploy_production.outputs.netlify-deploy-url }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Deploy production site
        id: deploy_production
        uses: ./
        with:
          auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          site: "pfi-bkm-personal-informationn-v1-mfe"
          dir: sites/production
          prod: true
