name: Init Netlify Project

on:
  push:
    branches:
      - master

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Netlify CLI
        run: npm install -g netlify-cli
      
      - name: Initialize Netlify Project
        run: netlify init --manual --name "pfi-bkm-personal-information-information-v1-mfe" --dir=dist --build "npm build"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

